M48
; DRILL file {KiCad (7.0.0)} date Sun Nov  5 01:23:12 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-05T01:23:12-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X5.0045Y-1.8744
X5.1955Y-1.8744
T2
X4.9927Y-1.7551
X5.2073Y-1.7551
T0
M30
